version: 0.2

env:
  variables:
    ECR_REPOSITORY: "firstrepo/firtspace"
  parameter-store:
    AWS_ACCOUNT_ID: "/sky-app/aws-account-id"
    AWS_REGION: "/sky-app/aws-region"

phases:
  install:
    runtime-versions:
      java: 17
    commands:
      - echo "Installing dependencies..."

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - echo "AWS Region: $AWS_REGION"
      - echo "AWS Account ID: $AWS_ACCOUNT_ID"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "Building the application..."
      - mvn clean package -DskipTests
      - echo "Building Docker image..."
      - docker build -t sky-app .
      - VERSION=$CODEBUILD_BUILD_NUMBER
      - docker tag sky-app:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/sky-app:$VERSION
      - docker tag sky-app:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/sky-app:latest

  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/sky-app:$VERSION
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/sky-app:latest
      - echo "Build completed successfully!"