version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file: mysql.env

    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - ./mysql-init/initDB.sql:/docker-entrypoint-initdb.d/initDB.sql
      - mysql-data:/var/lib/mysql

  sky-app:
    image: sky-app:1.0.0
    container_name: sky-app
    ports:
      - "8080:8080"
    env_file: sky-app.env

    depends_on:
      - redis
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:

