server:
  port: 8080


spring:
  mvc:
    static-path-pattern: /resources/static/**
  web:
    resources:
      static-locations: classpath:/static/
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${sky.datasource.url}
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}
  redis:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    password: ${sky.redis.password}
    database: ${sky.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    admin-secret-key: ${sky.jwt.admin-secret-key}
    admin-ttl: ${sky.jwt.admin-ttl}
    admin-token-name: ${sky.jwt.admin-token-name}
    user-secret-key: ${sky.jwt.user-secret-key}
    user-ttl: ${sky.jwt.user-ttl}
    user-token-name: ${sky.jwt.user-token-name}

  aws:
    s3:
      region: ${sky.aws.region}
      bucket-name: ${sky.aws.bucket-name}
  stripe:
    secret-key: ${sky.stripe.secret-key}

  wechat:
    secret: ${sky.wechat.secret}
    appid: ${sky.wechat.appid}